### PR TITLE
Don't warning when `rmb_fee` is used

### PR DESCRIPTION
**Pull request by agonzalezro**
It's possible to use the alipay gateway just sending the `rmb_fee`
parameter. The gem currently allow it but it will raise a warning when
it shouldn't.

Also, fix typo: Ailpay -> Alipay

### CODE REVIEW

**Comment by chloerei** [comment]
I can't find `rmb_fee` in alipay chinese document. Which document are you using? Please send me a link or a file.(Email in my personal page)

**Comment by agonzalezro** [comment]
Hi @chloerei, thanks for the quick reply.

I've made an screenshot:
screenshot 2015-04-09 12 27 36

If you want the full PDF I can forward it to you via email.

We are using it and it works. It's a way to specify the price in CNY/RMB when your account is on USD.

**Comment by chloerei** [comment]
Yes, please send my full PDF. English version is different from Chinese version, and I don't know how to get this version.

**Comment by chloerei** [comment]
Because you send me `create_forex_trade` service document, do you want to patch `create_forex_trade_url` method? This pull request modify `create_direct_pay_by_user_url` method, it's not same API.

**Comment by agonzalezro** [comment]
You are right, I didn't realise that I was not checking it on the forex method. I though that `rmb_fee` could be used anywhere.

**Comment by agonzalezro** [comment]
Thanks! This was quick :)

**Comment by chloerei** [comment]
Thanks for contribute!

I do some modify: remove `rmb_fee` check in `create_direct_pay_by_user_url` method(official document does not provide this param),  and unified use `check_optional_params`. 9b88900044b86dec9e73ab71f7a034f5288cc133

**Pull request merged**
